
export const MAP_CONSTANTS = {
  DEFAULT_ZOOM: 12,
  MAX_ZOOM: 18,
  MIN_ZOOM: 5,
  NEARBY_STATIONS_LIMIT: 5,
  CLUSTER_RADIUS: {
    HIGH_ZOOM: 40,
    MEDIUM_ZOOM: 60,
    LOW_ZOOM: 80
  },
  DISABLE_CLUSTERING_ZOOM: 13
} as const;

export const PERFORMANCE_THRESHOLDS = {
  SLOW_OPERATION: 1000,
  BUFFER_SIZE: 10
} as const;
